### ISSUE TITLE
Does not exit after translation

### ISSUE THREAD

**Issue by CsatiZoltan** [KevCui/translate-cli#4]
Trying your example with the Chromium-based Brave browser
```bash
./translate.js -p /usr/bin/brave-browser -t zh -s deepl 'stay the fuck home'
```
gives me the translated sentence
```
(node:7097) ExperimentalWarning: The fs.promises API is experimental
呆在家里
```
but does not exit. Why does it happen and how can I make it exit without closing the terminal and hence killing the process?

**Comment by KevCui** [comment]
Hi @CsatiZoltan, I quickly checked the script with brave browser and it works for me. I assume the error is coming from the dependency `puppeteer-core`. Could you please try to reinstall the latest version of `puppeteer-core` to see if it works?

**Comment by CsatiZoltan** [comment]
Hi. I installed the dependencies as given in the README:
```bash
npm i puppeteer-core commander
```
which gives
```bash
npm WARN saveError ENOENT: no such file or directory, open '/home/zoltan/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/zoltan/package.json'
npm WARN ws@7.4.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN zoltan No description
npm WARN zoltan No repository field.
npm WARN zoltan No README data
npm WARN zoltan No license field.

+ puppeteer-core@8.0.0
+ commander@7.1.0
updated 2 packages and audited 95 packages in 0.84s
found 0 vulnerabilities
```
[Version 8](https://github.com/puppeteer/puppeteer/releases/tag/v8.0.0) is the latest.

**Comment by KevCui** [comment]
Hi @CsatiZoltan. thanks for the info. And after that, run the script works or shows you the same error as well?

**Comment by CsatiZoltan** [comment]
The same happens. As you can see in the video below, I get the translated text but it does not exit.

https://user-images.githubusercontent.com/12742890/109350182-5d7f5780-7877-11eb-9a06-63a558c22d73.mp4

**Comment by KevCui** [comment]
@CsatiZoltan Ok, weird. I will take another look if it's something wrong in the script. By the way, you don't need to close the terminal, to kill the running process, `ctrl+c` can help.

**Comment by CsatiZoltan** [comment]
Yes, that's true...

**Comment by KevCui** [comment]
@CsatiZoltan ok, it seems the old nodejs version may cause this error. What's your node version? `node -v`. I think if you upgrade it to the latest v14 or v15 may help to solve the error.

**Comment by CsatiZoltan** [comment]
I have `v10.13.0`. How can I update it safely (I don't want to mess up my installation)?

**Comment by KevCui** [comment]
@CsatiZoltan You may try to use `nvm` https://github.com/nvm-sh/nvm, it can help you to switch between different nodejs version quickly.

**Comment by CsatiZoltan** [comment]
Trying with version `v15.10.0`, I don't get the `(node:7097) ExperimentalWarning: The fs.promises API is experimental` warning any more but the process still doesn't finish by itself.

**Comment by KevCui** [comment]
Hi @CsatiZoltan, It looks like we are having a steady progress :smile:

I do not see any reason why the browser is not closed. As you can see in the `translate.js`, there is no other code between showing translated result and closing browser. I need more info, if you can help to run this command `env DEBUG="puppeteer:*" env DEBUG_COLORS=false ./translate.js -p /usr/bin/brave-browser -t de 'hold my beer' 2>&1 | grep -v '"Network' > debug.log`. This line of command will generate debug logs into `debug.log` file.  If you could post the logs here, I will take a further look.

**Comment by KevCui** [comment]
Hi @CsatiZoltan, I just updated `translate.js` to simplify some codes. It may solve your issue indirectly. Give it a try?

**Comment by CsatiZoltan** [comment]
Hi. I executed
```bash
env DEBUG="puppeteer:*" env DEBUG_COLORS=false ./translate.js -p /usr/bin/brave-browser -t de 'hold my beer' 2>&1 | grep -v '"Network' > debug.log
```
with the new version of the `translate.js` script, but it didn't seem to solve the issue. Here is the log file.
[debug.log](https://github.com/KevCui/translate-cli/files/6056332/debug.log)

**Comment by KevCui** [comment]
Hi @CsatiZoltan, thanks for testing. Ehm... the attached debug.log is truncated in the middle of running process.

Could you please run this line of command `env DEBUG="puppeteer:*" env DEBUG_COLORS=false ./translate.js -p /usr/bin/brave-browser -t de 'hold my beer' 2>&1 | grep -v '"Network' | tee debug.log`, it will print out the logs on the screen and meanwhile logging them into `debug.log`. Please leave the script  run for another 5 seconds after seeing the translation text `Halte mein Bier`. If it's not finished after 5 seconds, then kill the script. It would be appreciated if you could post result with debug.log. Thanks!

**Comment by milahu** [comment]
shameless workaround: replace puppeteer with jsdom @ https://github.com/milahu/deepl-client-jsdom

```
time echo $(echo 'humans are the virus' | node deepl-cli.js en zh)
人类是病毒

real    0m5.499s
```

**Comment by KevCui** [comment]
@milahu Use jsdom to replace puppeteer is a good idea in general. However, looking at the exec time ~5s, it feels there is still the potential to improve the speed :)

**Comment by milahu** [comment]
im trying ^^

```
echo 'humans are the virus' | node deepl-cli.js en zh --time

time: 2.392 sec to require jsdom
time: 0.018 sec to require getPath
time sum: 2.425 sec to parse script

time: 0.007 sec to read stdin
time: 0.89 sec to load jsdom.fromURL
time: 1.275 sec to load document
time: 1.551 sec to get targetText
time sum: 3.727 sec to get targetText

time sum: 6.152 sec to parse script and get targetText

人类是病毒
```

`require jsdom` is faster with snapshots
`require jsdom` `load jsdom.fromURL` `load document` can be avoided by talking to the backend directly
... or by running the client as a daemon

`get targetText` is the bottleneck, mostly waiting for the deepl server
at least 0.3 sec of `get targetText` is rate limiting on the client side 
-> debug mode says `[Dict] Delaying dictionary lookup by 300`

so, this short input could be translated in 1.2 sec

how fast does puppeteer load? ; )

edit: after using the official interface for some time with no trouble,
i just got my IP blocked, by directly talking to the private API with `node deepl-cli.js --hacky`
probably cos at first, i skipped the 300 ms delay before calling `dict.deepl.com`

**Comment by KevCui** [comment]
Hey all, since there hasn’t been any information in the last three years, I’m closing this issue. If you encounter the same problem or have a different issue, feel free to leave a comment here or open a new one. Thanks.
