### ISSUE TITLE
encode text for deepl: escape slash and backslash

### ISSUE THREAD

**Issue by milahu** [KevCui/translate-cli#5]
when we enter `/` or `\` in the deepl web interface, these are escaped in the url

i encode the source text for deepl with

```js
// https://github.com/iansan5653/unraw/issues/29
// deepl.com:
//   / -> \/
//   \ -> \\
function deeplBackslashEncode(str) {
  let res = '';
  for (let i = 0; i < str.length; i++) {
    const char16bit = str[i];
    const code = char16bit.charCodeAt(0);
    res += (
      (code == 47) ? '\\/' : // forward slash
      (code == 92) ? '\\\\' : // backslash
      char16bit
    );
  }
  return res;
}

const translateUrl = t => (
  translatorName == 'google' ? `https://translate.google.com/?sl=${sourceLang}&tl=${targetLang}&text=${encodeURIComponent(t)}&op=translate` :
  translatorName == 'deepl' ? `https://www.deepl.com/translator#${sourceLang}/${targetLang}/${encodeURIComponent(deeplBackslashEncode(t))}` :
  '#invalid-translatorName'
);
```

**Comment by KevCui** [comment]
Hi @milahu, thanks for your suggestion. The latest commit should fix the problem of slash in DeepL URL. I checked backslash as well, seems it doesn't cause any problem. So I leave backslash as it is.

**Comment by milahu** [comment]
i also got rid off puppeteer : )

https://github.com/milahu/deepl-client-jsdom

just had to workaround a bug in jsdom and a bug in deepl

**Comment by milahu** [comment]
> I checked backslash as well, seems it doesn't cause any problem. So I leave backslash as it is.

not escaping backslash could produce unwanted results ...
e.g. `\not what i wanted` turned into `<newline>ot what i wanted`

the deepl webinterface also does escape backslash

**Comment by KevCui** [comment]
Hi @milahu, I tried your example:

```
./translate.js -s deepl -t es "\not what i wanted"
\no es lo que quería
```

The response looks fine. The backslash probably is handled by DeepL when parsing encoded URI.

**Comment by milahu** [comment]
there is one case where it breaks:

```
node translate.js -p $(which chromium) -f en -t de -s deepl "hello \/ world"
hallo \
```

**Comment by KevCui** [comment]
Hi @milahu thanks for the example. Issue has been fixed in the latest commit.
